/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllEficacia;
import controller.ControllObjetoRisco;
import controller.ControllRisco;
import controller.ControllUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Racca
 */
public class CriarRelacao extends javax.swing.JFrame {

    
    private ControllObjetoRisco objetoRisco= new ControllObjetoRisco();
    private ControllEficacia eficacia = new ControllEficacia();
    private ControllUsuario use=new ControllUsuario();
    private JPanel anterior;
    
    public CriarRelacao() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCard = new javax.swing.JPanel();
        jPanelObjetoRisco = new javax.swing.JPanel();
        jComboBoxObjeto = new javax.swing.JComboBox<>();
        jComboBoxImpacto = new javax.swing.JComboBox<>();
        jComboBoxProbabilidade = new javax.swing.JComboBox<>();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelNomeRisco = new javax.swing.JLabel();
        jLabelObjeto = new javax.swing.JLabel();
        jLabelImpacto = new javax.swing.JLabel();
        jLabelProbabilidade = new javax.swing.JLabel();
        jPanelEficacia = new javax.swing.JPanel();
        jComboBoxObjeto2 = new javax.swing.JComboBox<>();
        jComboBoxEficacia = new javax.swing.JComboBox<>();
        jButtonAdicionar1 = new javax.swing.JButton();
        jButtonSair1 = new javax.swing.JButton();
        jLabelNomeMitigacao = new javax.swing.JLabel();
        jComboBoxRisco = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelCard.setLayout(new java.awt.CardLayout());

        jPanelObjetoRisco.setPreferredSize(new java.awt.Dimension(400, 300));

        jComboBoxObjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxObjetoActionPerformed(evt);
            }
        });

        jComboBoxImpacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixo", "Médio", "Alto" }));
        jComboBoxImpacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxImpactoActionPerformed(evt);
            }
        });

        jComboBoxProbabilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixo", "Médio", "Alto" }));
        jComboBoxProbabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProbabilidadeActionPerformed(evt);
            }
        });

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelNomeRisco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomeRisco.setText("Risco: Nome Risco");

        jLabelObjeto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelObjeto.setText("Objeto Relacionado");

        jLabelImpacto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelImpacto.setText("Impacto");

        jLabelProbabilidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProbabilidade.setText("Probabilidade");

        javax.swing.GroupLayout jPanelObjetoRiscoLayout = new javax.swing.GroupLayout(jPanelObjetoRisco);
        jPanelObjetoRisco.setLayout(jPanelObjetoRiscoLayout);
        jPanelObjetoRiscoLayout.setHorizontalGroup(
            jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelObjetoRiscoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanelObjetoRiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelObjetoRiscoLayout.createSequentialGroup()
                            .addGroup(jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxImpacto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelImpacto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelProbabilidade)
                                .addComponent(jComboBoxProbabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelNomeRisco)
                    .addComponent(jLabelObjeto))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelObjetoRiscoLayout.setVerticalGroup(
            jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelObjetoRiscoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelNomeRisco)
                .addGap(15, 15, 15)
                .addComponent(jLabelObjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImpacto)
                    .addComponent(jLabelProbabilidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxImpacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProbabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanelObjetoRiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanelCard.add(jPanelObjetoRisco, "card2");

        jComboBoxObjeto2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxObjeto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxObjeto2ActionPerformed(evt);
            }
        });

        jComboBoxEficacia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma", "Pequena", "Média", "Grande", "Perfeita" }));
        jComboBoxEficacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEficaciaActionPerformed(evt);
            }
        });

        jButtonAdicionar1.setText("Adicionar");
        jButtonAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionar1ActionPerformed(evt);
            }
        });

        jButtonSair1.setText("Sair");
        jButtonSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair1ActionPerformed(evt);
            }
        });

        jLabelNomeMitigacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomeMitigacao.setText("Mitigação: Nome Mitigacao");

        jComboBoxRisco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRiscoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEficaciaLayout = new javax.swing.GroupLayout(jPanelEficacia);
        jPanelEficacia.setLayout(jPanelEficaciaLayout);
        jPanelEficaciaLayout.setHorizontalGroup(
            jPanelEficaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEficaciaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanelEficaciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEficaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxObjeto2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeMitigacao)
                    .addComponent(jComboBoxRisco, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEficaciaLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jComboBoxEficacia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelEficaciaLayout.setVerticalGroup(
            jPanelEficaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEficaciaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelNomeMitigacao)
                .addGap(35, 35, 35)
                .addComponent(jComboBoxObjeto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jComboBoxRisco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxEficacia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanelEficaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanelCard.add(jPanelEficacia, "card3");

        getContentPane().add(jPanelCard, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxObjetoActionPerformed

    private void jComboBoxImpactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxImpactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxImpactoActionPerformed

    private void jComboBoxProbabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProbabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProbabilidadeActionPerformed

    private void jComboBoxObjeto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxObjeto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxObjeto2ActionPerformed

    private void jComboBoxEficaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEficaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEficaciaActionPerformed

    private void jComboBoxRiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRiscoActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        try {
            if(objetoRisco.adicionarRelacao(this)){
                JOptionPane.showMessageDialog(null, "Adicionado com Sucesso", "Adicionado!", JOptionPane.INFORMATION_MESSAGE, null);
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao Adicionar Relação", "Erro ao Adicionar!", JOptionPane.ERROR_MESSAGE, null);
                
            }
        } catch (CloneNotSupportedException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Adicionar Relação", "Erro ao Adicionar!", JOptionPane.ERROR_MESSAGE, null);
        }
        
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        try {
            objetoRisco.fechar(this);
        } catch (CloneNotSupportedException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao Fechar Janela", "Erro ao Fechar!", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair1ActionPerformed
        try {
            eficacia.fechar(this);
        } catch (CloneNotSupportedException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao Fechar Janela", "Erro ao Fechar!", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_jButtonSair1ActionPerformed

    private void jButtonAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionar1ActionPerformed
         try {
            if(eficacia.adicionarEficacia(this)){
                JOptionPane.showMessageDialog(null, "Adicionado com Sucesso", "Adicionado!", JOptionPane.INFORMATION_MESSAGE, null);
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao Adicionar Eficacia", "Erro ao Adicionar!", JOptionPane.ERROR_MESSAGE, null);
                
            }
        } catch (CloneNotSupportedException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Adicionar Eficacia", "Erro ao Adicionar!", JOptionPane.ERROR_MESSAGE, null);
        }
        
    }//GEN-LAST:event_jButtonAdicionar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarRelacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAdicionar1;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSair1;
    private javax.swing.JComboBox<String> jComboBoxEficacia;
    private javax.swing.JComboBox<String> jComboBoxImpacto;
    private javax.swing.JComboBox<String> jComboBoxObjeto;
    private javax.swing.JComboBox<String> jComboBoxObjeto2;
    private javax.swing.JComboBox<String> jComboBoxProbabilidade;
    private javax.swing.JComboBox<String> jComboBoxRisco;
    private javax.swing.JLabel jLabelImpacto;
    private javax.swing.JLabel jLabelNomeMitigacao;
    private javax.swing.JLabel jLabelNomeRisco;
    private javax.swing.JLabel jLabelObjeto;
    private javax.swing.JLabel jLabelProbabilidade;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JPanel jPanelEficacia;
    private javax.swing.JPanel jPanelObjetoRisco;
    // End of variables declaration//GEN-END:variables

    

    public ControllUsuario getUse() {
        return use;
    }

    public JPanel getAnterior() {
        return anterior;
    }

    public JComboBox<String> getjComboBoxEficacia() {
        return jComboBoxEficacia;
    }

    public JComboBox<String> getjComboBoxImpacto() {
        return jComboBoxImpacto;
    }

    public JComboBox<String> getjComboBoxObjeto() {
        return jComboBoxObjeto;
    }

    public JComboBox<String> getjComboBoxObjeto2() {
        return jComboBoxObjeto2;
    }

    public JComboBox<String> getjComboBoxProbabilidade() {
        return jComboBoxProbabilidade;
    }

    public JComboBox<String> getjComboBoxRisco() {
        return jComboBoxRisco;
    }

    public JLabel getjLabelNomeMitigacao() {
        return jLabelNomeMitigacao;
    }

    public JLabel getjLabelNomeRisco() {
        return jLabelNomeRisco;
    }

    public JPanel getjPanelEficacia() {
        return jPanelEficacia;
    }

    public JPanel getjPanelObjetoRisco() {
        return jPanelObjetoRisco;
    }

    public ControllObjetoRisco getObjetoRisco() {
        return objetoRisco;
    }

    public void setObjetoRisco(ControllObjetoRisco objetoRisco) {
        this.objetoRisco = objetoRisco;
    }

    

    public void setUse(ControllUsuario use) {
        this.use = use;
    }

    public void setAnterior(risco anterior) {
        this.anterior = anterior;
    }

    public void setjComboBoxEficacia(JComboBox<String> jComboBoxEficacia) {
        this.jComboBoxEficacia = jComboBoxEficacia;
    }

    public void setjComboBoxImpacto(JComboBox<String> jComboBoxImpacto) {
        this.jComboBoxImpacto = jComboBoxImpacto;
    }

    public void setjComboBoxObjeto(JComboBox<String> jComboBoxObjeto) {
        this.jComboBoxObjeto = jComboBoxObjeto;
    }

    public void setjComboBoxObjeto2(JComboBox<String> jComboBoxObjeto2) {
        this.jComboBoxObjeto2 = jComboBoxObjeto2;
    }

    public void setjComboBoxProbabilidade(JComboBox<String> jComboBoxProbabilidade) {
        this.jComboBoxProbabilidade = jComboBoxProbabilidade;
    }

    public void setjComboBoxRisco(JComboBox<String> jComboBoxRisco) {
        this.jComboBoxRisco = jComboBoxRisco;
    }

    public void setjLabelNomeMitigacao(JLabel jLabelNomeMitigacao) {
        this.jLabelNomeMitigacao = jLabelNomeMitigacao;
    }

    public void setjLabelNomeRisco(JLabel jLabelNomeRisco) {
        this.jLabelNomeRisco = jLabelNomeRisco;
    }

    public void setjPanelEficacia(JPanel jPanelEficacia) {
        this.jPanelEficacia = jPanelEficacia;
    }

    public void setjPanelObjetoRisco(JPanel jPanelObjetoRisco) {
        this.jPanelObjetoRisco = jPanelObjetoRisco;
    }

    public ControllEficacia getEficacia() {
        return eficacia;
    }

    public void setEficacia(ControllEficacia eficacia) {
        this.eficacia = eficacia;
    }

    public void setAnterior(JPanel anterior) {
        this.anterior = anterior;
    }

    public JPanel getjPanelCard() {
        return jPanelCard;
    }

    


}
