/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllMapa;
import controller.ControllUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import view.ListaProcesso;

/**
 *
 * @author Racca
 */
    public class main extends javax.swing.JFrame {

        ControllUsuario use = new ControllUsuario();
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartao01 = new javax.swing.JPanel();
        tela00 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(880, 660));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("main"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        cartao01.setPreferredSize(new java.awt.Dimension(800, 600));
        cartao01.setLayout(new java.awt.CardLayout());

        tela00.setPreferredSize(new java.awt.Dimension(800, 600));

        lblLogin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Digite o Login ");
        lblLogin.setPreferredSize(new java.awt.Dimension(100, 100));

        lblSenha.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("Digite a senha ");

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFecha.setText("Fechar");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout tela00Layout = new javax.swing.GroupLayout(tela00);
        tela00.setLayout(tela00Layout);
        tela00Layout.setHorizontalGroup(
            tela00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela00Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(tela00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tela00Layout.createSequentialGroup()
                .addGroup(tela00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela00Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tela00Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tela00Layout.setVerticalGroup(
            tela00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela00Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(tela00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        lblLogin.getAccessibleContext().setAccessibleName("Digite a senha para Login:");

        cartao01.add(tela00, "tela00");

        getContentPane().add(cartao01, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String varLog=txtLogin.getText();
        String varSenha=txtSenha.getText();
        //comparar com o BD
        
        ListaProcesso prt01=new ListaProcesso();
        
        try { 
            //if(true){
            if(use.login(varLog, varSenha)){
                cartao01.removeAll();
                cartao01.add(prt01);
                txtLogin.setText("");
                txtSenha.setText("");
                prt01.setPrincipal(this);


                use.carregaFormulario(prt01);
                prt01.setUse(use);


                cartao01.repaint();
                cartao01.revalidate();

            }else{
                JOptionPane.showMessageDialog(null, "Login ou senha inválido", "Erro ao Logar!", JOptionPane.ERROR_MESSAGE, null);
            }
        } catch (CloneNotSupportedException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFechaActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if(txtSenha.getPassword().length>35){
           // JOptionPane.showMessageDialog(null,"Numero excessimo de Caracteres, limite de 35 caracteres","Erro na Senha",JOptionPane.ERROR_MESSAGE,null);
            char[] senha=txtSenha.getPassword();
            String novaSenha="";
            int i;
            for(i=0;i<36;i++){
               novaSenha+=senha[i];
            }
            txtSenha.setText(novaSenha);
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        if(txtLogin.getText().getBytes().length>50){
           // JOptionPane.showMessageDialog(null,"Numero excessimo de Caracteres, limite de 35 caracteres","Erro na Senha",JOptionPane.ERROR_MESSAGE,null);
            char[] nome=txtLogin.getText().toCharArray();
            String novoNome="";
            int i;
            for(i=0;i<51;i++){
               novoNome+=nome[i];
            }
            txtLogin.setText(novoNome);
        }
    }//GEN-LAST:event_txtLoginKeyPressed
    public void Logoff() {                                              
        if(use.logoff()){
            cartao01.removeAll();
            cartao01.add(tela00);
            cartao01.repaint();
            cartao01.revalidate();
        }else{
            JOptionPane.showMessageDialog(null, "Falha no Logoff", "Erro ao Deslogar!", JOptionPane.ERROR_MESSAGE, null);
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public JPanel getCartao01() {
        return cartao01;
    }

    public JPanel getTela00() {
        return tela00;
    }

    public void setCartao01(JPanel cartao01) {
        this.cartao01 = cartao01;
    }

    public void setTela00(JPanel tela00) {
        this.tela00 = tela00;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel cartao01;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel tela00;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
