/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllMapa;
import javax.swing.JList;

/**
 *
 * @author Racca
 */
public class mapaEficacia extends javax.swing.JPanel {

    private ControllMapa mapa=new ControllMapa();
    public mapaEficacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEficacia = new javax.swing.JLabel();
        jLabelRisco = new javax.swing.JLabel();
        jScrollPane40 = new javax.swing.JScrollPane();
        jList40 = new javax.swing.JList<>();
        jScrollPane20 = new javax.swing.JScrollPane();
        jList20 = new javax.swing.JList<>();
        jScrollPane30 = new javax.swing.JScrollPane();
        jList30 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        jScrollPane00 = new javax.swing.JScrollPane();
        jList00 = new javax.swing.JList<>();
        jScrollPane41 = new javax.swing.JScrollPane();
        jList41 = new javax.swing.JList<>();
        jScrollPane31 = new javax.swing.JScrollPane();
        jList31 = new javax.swing.JList<>();
        jScrollPane21 = new javax.swing.JScrollPane();
        jList21 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList11 = new javax.swing.JList<>();
        jScrollPane01 = new javax.swing.JScrollPane();
        jList01 = new javax.swing.JList<>();
        jScrollPane02 = new javax.swing.JScrollPane();
        jList02 = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList12 = new javax.swing.JList<>();
        jScrollPane22 = new javax.swing.JScrollPane();
        jList22 = new javax.swing.JList<>();
        jScrollPane32 = new javax.swing.JScrollPane();
        jList32 = new javax.swing.JList<>();
        jScrollPane42 = new javax.swing.JScrollPane();
        jList42 = new javax.swing.JList<>();
        jScrollPane03 = new javax.swing.JScrollPane();
        jList03 = new javax.swing.JList<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        jList13 = new javax.swing.JList<>();
        jScrollPane23 = new javax.swing.JScrollPane();
        jList23 = new javax.swing.JList<>();
        jScrollPane33 = new javax.swing.JScrollPane();
        jList33 = new javax.swing.JList<>();
        jScrollPane43 = new javax.swing.JScrollPane();
        jList43 = new javax.swing.JList<>();
        jScrollPane04 = new javax.swing.JScrollPane();
        jList04 = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        jList14 = new javax.swing.JList<>();
        jScrollPane24 = new javax.swing.JScrollPane();
        jList24 = new javax.swing.JList<>();
        jScrollPane34 = new javax.swing.JScrollPane();
        jList34 = new javax.swing.JList<>();
        jScrollPane44 = new javax.swing.JScrollPane();
        jList44 = new javax.swing.JList<>();
        jLabelRiscoMuitoPouco = new javax.swing.JLabel();
        jLabelRiscoPouco = new javax.swing.JLabel();
        jLabelRiscoMedio = new javax.swing.JLabel();
        jLabelRiscoGrande = new javax.swing.JLabel();
        jLabelRiscoMuitoGrande = new javax.swing.JLabel();
        jLabelEficaciaPerfeita = new javax.swing.JLabel();
        jLabelEficaciaAlta = new javax.swing.JLabel();
        jLabelEficaciaMedia = new javax.swing.JLabel();
        jLabelEficaciaPouca = new javax.swing.JLabel();
        jLabelEficaciaNenhuma = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelEficacia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEficacia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEficacia.setText("Eficacia");

        jLabelRisco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRisco.setText("Risco");

        jScrollPane40.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane40.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane40.setPreferredSize(new java.awt.Dimension(144, 101));

        jList40.setBackground(new java.awt.Color(255, 153, 0));
        jList40.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList40.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList40.setVisibleRowCount(4);
        jList40.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList40MouseMoved(evt);
            }
        });
        jScrollPane40.setViewportView(jList40);

        jScrollPane20.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane20.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane20.setPreferredSize(new java.awt.Dimension(144, 101));

        jList20.setBackground(new java.awt.Color(255, 255, 51));
        jList20.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList20.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList20.setVisibleRowCount(4);
        jList20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList20MouseMoved(evt);
            }
        });
        jScrollPane20.setViewportView(jList20);

        jScrollPane30.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane30.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane30.setPreferredSize(new java.awt.Dimension(144, 101));

        jList30.setBackground(new java.awt.Color(255, 255, 51));
        jList30.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList30.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList30.setVisibleRowCount(4);
        jList30.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList30MouseMoved(evt);
            }
        });
        jScrollPane30.setViewportView(jList30);

        jScrollPane10.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane10.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane10.setPreferredSize(new java.awt.Dimension(144, 101));

        jList10.setBackground(new java.awt.Color(51, 255, 0));
        jList10.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList10.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList10.setVisibleRowCount(4);
        jList10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList10MouseMoved(evt);
            }
        });
        jScrollPane10.setViewportView(jList10);

        jScrollPane00.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane00.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane00.setPreferredSize(new java.awt.Dimension(144, 101));

        jList00.setBackground(new java.awt.Color(0, 204, 204));
        jList00.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList00.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList00.setVisibleRowCount(4);
        jList00.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList00MouseMoved(evt);
            }
        });
        jScrollPane00.setViewportView(jList00);

        jScrollPane41.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane41.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane41.setPreferredSize(new java.awt.Dimension(144, 101));

        jList41.setBackground(new java.awt.Color(255, 153, 0));
        jList41.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList41.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList41.setVisibleRowCount(4);
        jList41.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList41MouseMoved(evt);
            }
        });
        jScrollPane41.setViewportView(jList41);

        jScrollPane31.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane31.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane31.setPreferredSize(new java.awt.Dimension(144, 101));

        jList31.setBackground(new java.awt.Color(255, 153, 0));
        jList31.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList31.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList31.setVisibleRowCount(4);
        jList31.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList31MouseMoved(evt);
            }
        });
        jScrollPane31.setViewportView(jList31);

        jScrollPane21.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane21.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane21.setPreferredSize(new java.awt.Dimension(144, 101));

        jList21.setBackground(new java.awt.Color(255, 255, 51));
        jList21.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList21.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList21.setVisibleRowCount(4);
        jList21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList21MouseMoved(evt);
            }
        });
        jScrollPane21.setViewportView(jList21);

        jScrollPane11.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane11.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane11.setPreferredSize(new java.awt.Dimension(144, 101));

        jList11.setBackground(new java.awt.Color(51, 255, 0));
        jList11.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList11.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList11.setVisibleRowCount(4);
        jList11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList11MouseMoved(evt);
            }
        });
        jScrollPane11.setViewportView(jList11);

        jScrollPane01.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane01.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane01.setPreferredSize(new java.awt.Dimension(144, 101));

        jList01.setBackground(new java.awt.Color(51, 255, 0));
        jList01.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList01.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList01.setVisibleRowCount(4);
        jList01.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList01MouseMoved(evt);
            }
        });
        jScrollPane01.setViewportView(jList01);

        jScrollPane02.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane02.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane02.setPreferredSize(new java.awt.Dimension(144, 101));

        jList02.setBackground(new java.awt.Color(255, 255, 51));
        jList02.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList02.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList02.setVisibleRowCount(4);
        jList02.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList02MouseMoved(evt);
            }
        });
        jScrollPane02.setViewportView(jList02);

        jScrollPane12.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane12.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane12.setPreferredSize(new java.awt.Dimension(144, 101));

        jList12.setBackground(new java.awt.Color(255, 255, 51));
        jList12.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList12.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList12.setVisibleRowCount(4);
        jList12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList12MouseMoved(evt);
            }
        });
        jScrollPane12.setViewportView(jList12);

        jScrollPane22.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane22.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane22.setPreferredSize(new java.awt.Dimension(144, 101));

        jList22.setBackground(new java.awt.Color(255, 255, 51));
        jList22.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList22.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList22.setVisibleRowCount(4);
        jList22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList22MouseMoved(evt);
            }
        });
        jScrollPane22.setViewportView(jList22);

        jScrollPane32.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane32.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane32.setPreferredSize(new java.awt.Dimension(144, 101));

        jList32.setBackground(new java.awt.Color(255, 153, 0));
        jList32.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList32.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList32.setVisibleRowCount(4);
        jList32.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList32MouseMoved(evt);
            }
        });
        jScrollPane32.setViewportView(jList32);

        jScrollPane42.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane42.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane42.setPreferredSize(new java.awt.Dimension(144, 101));

        jList42.setBackground(new java.awt.Color(255, 0, 0));
        jList42.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList42.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList42.setVisibleRowCount(4);
        jList42.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList42MouseMoved(evt);
            }
        });
        jScrollPane42.setViewportView(jList42);

        jScrollPane03.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane03.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane03.setPreferredSize(new java.awt.Dimension(144, 101));

        jList03.setBackground(new java.awt.Color(255, 255, 51));
        jList03.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList03.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList03.setVisibleRowCount(4);
        jList03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList03MouseMoved(evt);
            }
        });
        jScrollPane03.setViewportView(jList03);

        jScrollPane13.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane13.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane13.setPreferredSize(new java.awt.Dimension(144, 101));

        jList13.setBackground(new java.awt.Color(255, 153, 0));
        jList13.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList13.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList13.setVisibleRowCount(4);
        jList13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList13MouseMoved(evt);
            }
        });
        jScrollPane13.setViewportView(jList13);

        jScrollPane23.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane23.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane23.setPreferredSize(new java.awt.Dimension(144, 101));

        jList23.setBackground(new java.awt.Color(255, 153, 0));
        jList23.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList23.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList23.setVisibleRowCount(4);
        jList23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList23MouseMoved(evt);
            }
        });
        jScrollPane23.setViewportView(jList23);

        jScrollPane33.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane33.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane33.setPreferredSize(new java.awt.Dimension(144, 101));

        jList33.setBackground(new java.awt.Color(255, 0, 0));
        jList33.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList33.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList33.setVisibleRowCount(4);
        jList33.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList33MouseMoved(evt);
            }
        });
        jScrollPane33.setViewportView(jList33);

        jScrollPane43.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane43.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane43.setPreferredSize(new java.awt.Dimension(144, 101));

        jList43.setBackground(new java.awt.Color(255, 0, 0));
        jList43.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList43.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList43.setVisibleRowCount(4);
        jList43.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList43MouseMoved(evt);
            }
        });
        jScrollPane43.setViewportView(jList43);

        jScrollPane04.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane04.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane04.setPreferredSize(new java.awt.Dimension(144, 101));

        jList04.setBackground(new java.awt.Color(255, 153, 0));
        jList04.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList04.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList04.setVisibleRowCount(4);
        jList04.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList04MouseMoved(evt);
            }
        });
        jScrollPane04.setViewportView(jList04);

        jScrollPane14.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane14.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane14.setPreferredSize(new java.awt.Dimension(144, 101));

        jList14.setBackground(new java.awt.Color(255, 153, 0));
        jList14.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList14.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList14.setVisibleRowCount(4);
        jList14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList14MouseMoved(evt);
            }
        });
        jScrollPane14.setViewportView(jList14);

        jScrollPane24.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane24.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane24.setPreferredSize(new java.awt.Dimension(144, 101));

        jList24.setBackground(new java.awt.Color(255, 0, 0));
        jList24.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList24.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList24.setVisibleRowCount(4);
        jList24.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList24MouseMoved(evt);
            }
        });
        jScrollPane24.setViewportView(jList24);

        jScrollPane34.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane34.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane34.setPreferredSize(new java.awt.Dimension(144, 101));

        jList34.setBackground(new java.awt.Color(255, 0, 0));
        jList34.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList34.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList34.setVisibleRowCount(4);
        jList34.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList34MouseMoved(evt);
            }
        });
        jScrollPane34.setViewportView(jList34);

        jScrollPane44.setMaximumSize(new java.awt.Dimension(266, 200));
        jScrollPane44.setMinimumSize(new java.awt.Dimension(240, 174));
        jScrollPane44.setPreferredSize(new java.awt.Dimension(144, 101));

        jList44.setBackground(new java.awt.Color(255, 0, 0));
        jList44.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList44.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList44.setVisibleRowCount(4);
        jList44.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList44MouseMoved(evt);
            }
        });
        jScrollPane44.setViewportView(jList44);

        jLabelRiscoMuitoPouco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRiscoMuitoPouco.setText("Muito Pouco");

        jLabelRiscoPouco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRiscoPouco.setText("Pouco");

        jLabelRiscoMedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRiscoMedio.setText("Médio");

        jLabelRiscoGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRiscoGrande.setText("Grande");

        jLabelRiscoMuitoGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRiscoMuitoGrande.setText("Muito Grande");

        jLabelEficaciaPerfeita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEficaciaPerfeita.setText("Perfeita");

        jLabelEficaciaAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEficaciaAlta.setText("Alta");

        jLabelEficaciaMedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEficaciaMedia.setText("Média");

        jLabelEficaciaPouca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEficaciaPouca.setText("Pouca");

        jLabelEficaciaNenhuma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEficaciaNenhuma.setText("Nenhuma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEficacia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelRisco)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRiscoMuitoPouco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRiscoPouco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelRiscoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRiscoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRiscoMuitoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEficaciaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEficaciaPouca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEficaciaMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelEficaciaPerfeita, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEficaciaNenhuma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEficacia)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelEficaciaNenhuma)
                        .addGap(92, 92, 92)
                        .addComponent(jLabelEficaciaPouca)
                        .addGap(93, 93, 93)
                        .addComponent(jLabelEficaciaMedia)
                        .addGap(91, 91, 91)
                        .addComponent(jLabelEficaciaAlta)
                        .addGap(96, 96, 96)
                        .addComponent(jLabelEficaciaPerfeita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRiscoMuitoPouco)
                    .addComponent(jLabelRiscoPouco)
                    .addComponent(jLabelRiscoMedio)
                    .addComponent(jLabelRiscoGrande)
                    .addComponent(jLabelRiscoMuitoGrande)
                    .addComponent(jLabelRisco))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList40MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList40MouseMoved
        if(jList40.getSelectedIndex()!=-1){
            int indx=jList40.getSelectedIndex();
            mapa.dialogEficacia(0,4, indx);
            jList40.clearSelection();
        }
    }//GEN-LAST:event_jList40MouseMoved

    private void jList24MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList24MouseMoved
        if(jList24.getSelectedIndex()!=-1){
            int indx=jList24.getSelectedIndex();
            mapa.dialogEficacia(4,2, indx);
            jList24.clearSelection();
        }
    }//GEN-LAST:event_jList24MouseMoved

    private void jList41MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList41MouseMoved
        if(jList41.getSelectedIndex()!=-1){
            int indx=jList41.getSelectedIndex();
            mapa.dialogEficacia(1,4, indx);
            jList41.clearSelection();
        }
    }//GEN-LAST:event_jList41MouseMoved

    private void jList42MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList42MouseMoved
        if(jList42.getSelectedIndex()!=-1){
            int indx=jList42.getSelectedIndex();
            mapa.dialogEficacia(2,4, indx);
            jList42.clearSelection();
        }
    }//GEN-LAST:event_jList42MouseMoved

    private void jList43MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList43MouseMoved
        if(jList43.getSelectedIndex()!=-1){
            int indx=jList43.getSelectedIndex();
            mapa.dialogEficacia(3,4, indx);
            jList43.clearSelection();
        }
    }//GEN-LAST:event_jList43MouseMoved

    private void jList44MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList44MouseMoved
       if(jList44.getSelectedIndex()!=-1){
            int indx=jList44.getSelectedIndex();
            mapa.dialogEficacia(4,4, indx);
            jList44.clearSelection();
        }
    }//GEN-LAST:event_jList44MouseMoved

    private void jList30MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList30MouseMoved
        if(jList30.getSelectedIndex()!=-1){
            int indx=jList30.getSelectedIndex();
            mapa.dialogEficacia(0,3, indx);
            jList30.clearSelection();
        }
    }//GEN-LAST:event_jList30MouseMoved

    private void jList31MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList31MouseMoved
        if(jList31.getSelectedIndex()!=-1){
            int indx=jList31.getSelectedIndex();
            mapa.dialogEficacia(1,3, indx);
            jList31.clearSelection();
        }
    }//GEN-LAST:event_jList31MouseMoved

    private void jList32MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList32MouseMoved
        if(jList32.getSelectedIndex()!=-1){
            int indx=jList32.getSelectedIndex();
            mapa.dialogEficacia(2,3, indx);
            jList32.clearSelection();
        }
    }//GEN-LAST:event_jList32MouseMoved

    private void jList33MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList33MouseMoved
        if(jList33.getSelectedIndex()!=-1){
            int indx=jList33.getSelectedIndex();
            mapa.dialogEficacia(3,3, indx);
            jList33.clearSelection();
        }
    }//GEN-LAST:event_jList33MouseMoved

    private void jList34MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList34MouseMoved
        if(jList34.getSelectedIndex()!=-1){
            int indx=jList34.getSelectedIndex();
            mapa.dialogEficacia(4,3, indx);
            jList34.clearSelection();
        }
    }//GEN-LAST:event_jList34MouseMoved

    private void jList20MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList20MouseMoved
        if(jList20.getSelectedIndex()!=-1){
            int indx=jList20.getSelectedIndex();
            mapa.dialogEficacia(0,2, indx);
            jList20.clearSelection();
        }
    }//GEN-LAST:event_jList20MouseMoved

    private void jList21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList21MouseMoved
        if(jList21.getSelectedIndex()!=-1){
            int indx=jList21.getSelectedIndex();
            mapa.dialogEficacia(1,2, indx);
            jList21.clearSelection();
        }
    }//GEN-LAST:event_jList21MouseMoved

    private void jList22MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList22MouseMoved
       if(jList22.getSelectedIndex()!=-1){
            int indx=jList22.getSelectedIndex();
            mapa.dialogEficacia(2,2, indx);
            jList22.clearSelection();
        }
    }//GEN-LAST:event_jList22MouseMoved

    private void jList23MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList23MouseMoved
       if(jList23.getSelectedIndex()!=-1){
            int indx=jList23.getSelectedIndex();
            mapa.dialogEficacia(3,2, indx);
            jList23.clearSelection();
        }
    }//GEN-LAST:event_jList23MouseMoved

    private void jList10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList10MouseMoved
        if(jList10.getSelectedIndex()!=-1){
            int indx=jList10.getSelectedIndex();
            mapa.dialogEficacia(0,1, indx);
            jList10.clearSelection();
        }
    }//GEN-LAST:event_jList10MouseMoved

    private void jList11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList11MouseMoved
        if(jList11.getSelectedIndex()!=-1){
            int indx=jList11.getSelectedIndex();
            mapa.dialogEficacia(1,1, indx);
            jList11.clearSelection();
        }
    }//GEN-LAST:event_jList11MouseMoved

    private void jList12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList12MouseMoved
        if(jList12.getSelectedIndex()!=-1){
            int indx=jList12.getSelectedIndex();
            mapa.dialogEficacia(2,1, indx);
            jList12.clearSelection();
        }
    }//GEN-LAST:event_jList12MouseMoved

    private void jList13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList13MouseMoved
        if(jList13.getSelectedIndex()!=-1){
            int indx=jList13.getSelectedIndex();
            mapa.dialogEficacia(3,1, indx);
            jList13.clearSelection();
        }
    }//GEN-LAST:event_jList13MouseMoved

    private void jList14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList14MouseMoved
       if(jList14.getSelectedIndex()!=-1){
            int indx=jList14.getSelectedIndex();
            mapa.dialogEficacia(4,1, indx);
            jList14.clearSelection();
        }
    }//GEN-LAST:event_jList14MouseMoved

    private void jList00MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList00MouseMoved
        if(jList00.getSelectedIndex()!=-1){
            int indx=jList00.getSelectedIndex();
            mapa.dialogEficacia(0,0, indx);
            jList00.clearSelection();
        }
    }//GEN-LAST:event_jList00MouseMoved

    private void jList01MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList01MouseMoved
        if(jList01.getSelectedIndex()!=-1){
            int indx=jList01.getSelectedIndex();
            mapa.dialogEficacia(1,0, indx);
            jList01.clearSelection();
        }
    }//GEN-LAST:event_jList01MouseMoved

    private void jList02MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList02MouseMoved
        if(jList02.getSelectedIndex()!=-1){
            int indx=jList02.getSelectedIndex();
            mapa.dialogEficacia(2,0, indx);
            jList02.clearSelection();
        }
    }//GEN-LAST:event_jList02MouseMoved

    private void jList03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList03MouseMoved
       if(jList03.getSelectedIndex()!=-1){
            int indx=jList03.getSelectedIndex();
            mapa.dialogEficacia(3,0, indx);
            jList03.clearSelection();
        }
    }//GEN-LAST:event_jList03MouseMoved

    private void jList04MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList04MouseMoved
        if(jList04.getSelectedIndex()!=-1){
            int indx=jList04.getSelectedIndex();
            mapa.dialogEficacia(4,0, indx);
            jList04.clearSelection();
        }
    }//GEN-LAST:event_jList04MouseMoved

    public JList<String> getjList00() {
        return jList00;
    }

    public JList<String> getjList01() {
        return jList01;
    }

    public JList<String> getjList02() {
        return jList02;
    }

    public JList<String> getjList03() {
        return jList03;
    }

    public JList<String> getjList04() {
        return jList04;
    }

    public JList<String> getjList10() {
        return jList10;
    }

    public JList<String> getjList11() {
        return jList11;
    }

    public JList<String> getjList12() {
        return jList12;
    }

    public JList<String> getjList13() {
        return jList13;
    }

    public JList<String> getjList14() {
        return jList14;
    }

    public JList<String> getjList20() {
        return jList20;
    }

    public JList<String> getjList21() {
        return jList21;
    }

    public JList<String> getjList22() {
        return jList22;
    }

    public JList<String> getjList23() {
        return jList23;
    }

    public JList<String> getjList24() {
        return jList24;
    }

    public JList<String> getjList30() {
        return jList30;
    }

    public JList<String> getjList31() {
        return jList31;
    }

    public JList<String> getjList32() {
        return jList32;
    }

    public JList<String> getjList33() {
        return jList33;
    }

    public JList<String> getjList34() {
        return jList34;
    }

    public JList<String> getjList40() {
        return jList40;
    }

    public void setMapa(ControllMapa mapa) {
        this.mapa = mapa;
    }

    public ControllMapa getMapa() {
        return mapa;
    }

    public JList<String> getjList41() {
        return jList41;
    }

    public JList<String> getjList42() {
        return jList42;
    }

    public JList<String> getjList43() {
        return jList43;
    }

    public JList<String> getjList44() {
        return jList44;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEficacia;
    private javax.swing.JLabel jLabelEficaciaAlta;
    private javax.swing.JLabel jLabelEficaciaMedia;
    private javax.swing.JLabel jLabelEficaciaNenhuma;
    private javax.swing.JLabel jLabelEficaciaPerfeita;
    private javax.swing.JLabel jLabelEficaciaPouca;
    private javax.swing.JLabel jLabelRisco;
    private javax.swing.JLabel jLabelRiscoGrande;
    private javax.swing.JLabel jLabelRiscoMedio;
    private javax.swing.JLabel jLabelRiscoMuitoGrande;
    private javax.swing.JLabel jLabelRiscoMuitoPouco;
    private javax.swing.JLabel jLabelRiscoPouco;
    private javax.swing.JList<String> jList00;
    private javax.swing.JList<String> jList01;
    private javax.swing.JList<String> jList02;
    private javax.swing.JList<String> jList03;
    private javax.swing.JList<String> jList04;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList11;
    private javax.swing.JList<String> jList12;
    private javax.swing.JList<String> jList13;
    private javax.swing.JList<String> jList14;
    private javax.swing.JList<String> jList20;
    private javax.swing.JList<String> jList21;
    private javax.swing.JList<String> jList22;
    private javax.swing.JList<String> jList23;
    private javax.swing.JList<String> jList24;
    private javax.swing.JList<String> jList30;
    private javax.swing.JList<String> jList31;
    private javax.swing.JList<String> jList32;
    private javax.swing.JList<String> jList33;
    private javax.swing.JList<String> jList34;
    private javax.swing.JList<String> jList40;
    private javax.swing.JList<String> jList41;
    private javax.swing.JList<String> jList42;
    private javax.swing.JList<String> jList43;
    private javax.swing.JList<String> jList44;
    private javax.swing.JScrollPane jScrollPane00;
    private javax.swing.JScrollPane jScrollPane01;
    private javax.swing.JScrollPane jScrollPane02;
    private javax.swing.JScrollPane jScrollPane03;
    private javax.swing.JScrollPane jScrollPane04;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    // End of variables declaration//GEN-END:variables
}
