/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllMapa;
import controller.ControllProcessos;
import javax.swing.JOptionPane;
import model.ModelProcessos;

/**
 *
 * @author Racca
 */
public class mapa extends javax.swing.JFrame {

   private ControllMapa mapa=new ControllMapa();
    ControllProcessos processo;
    
    public mapa() {
        
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public mapa(ControllProcessos proc) {
        processo=proc;
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCard0 = new javax.swing.JPanel();
        jPanelCard1 = new javax.swing.JPanel();
        jButtonRisco = new javax.swing.JButton();
        jButtonEficacia = new javax.swing.JButton();
        jLabelTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300450, 24000));
        setMinimumSize(new java.awt.Dimension(300, 150));
        setPreferredSize(new java.awt.Dimension(450, 240));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelCard0.setLayout(new java.awt.CardLayout());

        jPanelCard1.setMaximumSize(new java.awt.Dimension(300, 150));
        jPanelCard1.setPreferredSize(new java.awt.Dimension(300, 150));

        jButtonRisco.setText("Risco");
        jButtonRisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRiscoActionPerformed(evt);
            }
        });

        jButtonEficacia.setText("Eficacia");
        jButtonEficacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEficaciaActionPerformed(evt);
            }
        });

        jLabelTexto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTexto.setText("Deseja abrir qual mapa?");

        javax.swing.GroupLayout jPanelCard1Layout = new javax.swing.GroupLayout(jPanelCard1);
        jPanelCard1.setLayout(jPanelCard1Layout);
        jPanelCard1Layout.setHorizontalGroup(
            jPanelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCard1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButtonRisco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jButtonEficacia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCard1Layout.createSequentialGroup()
                .addComponent(jLabelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCard1Layout.setVerticalGroup(
            jPanelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCard1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTexto)
                .addGap(65, 65, 65)
                .addGroup(jPanelCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEficacia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRisco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanelCard0.add(jPanelCard1, "card2");

        getContentPane().add(jPanelCard0, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRiscoActionPerformed
        
        mapaRisco map=processo.exibirMapaRisco();
        if(map!=null){
            map.setMapa(mapa);
            setSize(840,630);
            jPanelCard0.removeAll();
            jPanelCard0.add(map);
            jPanelCard0.repaint();
            jPanelCard0.revalidate();
            
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao Exibir Mapa", "Erro no Mapa!", JOptionPane.ERROR_MESSAGE, null);
        
        }
    }//GEN-LAST:event_jButtonRiscoActionPerformed

    private void jButtonEficaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEficaciaActionPerformed
        
        mapaEficacia map=processo.exibirMapaEficacia();
        if(map!=null){
            map.setMapa(mapa);
            setSize(840,630);
            jPanelCard0.removeAll();
            jPanelCard0.add(map);
            jPanelCard0.repaint();
            jPanelCard0.revalidate();
            
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao Exibir Mapa", "Erro no Mapa!", JOptionPane.ERROR_MESSAGE, null);
        
        }
    }//GEN-LAST:event_jButtonEficaciaActionPerformed

    public ControllMapa getMapa() {
        return mapa;
    }

    public void setMapa(ControllMapa mapa) {
        this.mapa = mapa;
    }

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEficacia;
    private javax.swing.JButton jButtonRisco;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JPanel jPanelCard0;
    private javax.swing.JPanel jPanelCard1;
    // End of variables declaration//GEN-END:variables

    public void setProcesso(ControllProcessos processo) {
        this.processo = processo;
    }


}
