/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllProcessos;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Racca
 */
public class MenuPrincipal extends javax.swing.JPanel {

    ControllProcessos processo=new ControllProcessos();
    private main principal;
    
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonObjeto = new javax.swing.JButton();
        jButtonRisco = new javax.swing.JButton();
        jButtonMitigacao = new javax.swing.JButton();
        jButtonMapa = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelNomeProcesso = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jButtonObjeto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonObjeto.setText("Objeto");
        jButtonObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObjetoActionPerformed(evt);
            }
        });

        jButtonRisco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRisco.setText("Risco");
        jButtonRisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRiscoActionPerformed(evt);
            }
        });

        jButtonMitigacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMitigacao.setText("Mitigação");
        jButtonMitigacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMitigacaoActionPerformed(evt);
            }
        });

        jButtonMapa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMapa.setText("Vizualizar Mapa");
        jButtonMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapaActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelNomeProcesso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomeProcesso.setText("Processo: Nome do Processo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMitigacao, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRisco, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNomeProcesso)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelNomeProcesso)
                .addGap(70, 70, 70)
                .addComponent(jButtonObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonRisco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonMitigacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       if(processo.sair(principal)){
       }else{
           JOptionPane.showMessageDialog(null, "Erro ao voltar pro Usuario", "Erro ao Sair!", JOptionPane.ERROR_MESSAGE, null);
        
       }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapaActionPerformed
        mapa frame = new mapa(processo);
        
        frame.setVisible(true);  
    }//GEN-LAST:event_jButtonMapaActionPerformed

    private void jButtonObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObjetoActionPerformed
        try {
            processo.abrirObjeto(principal);
        } catch (CloneNotSupportedException ex) {
           JOptionPane.showMessageDialog(null, "Falha no Objeto", "Erro ao abrir Objeto!", JOptionPane.ERROR_MESSAGE, null);
            
        }
    }//GEN-LAST:event_jButtonObjetoActionPerformed

    private void jButtonRiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRiscoActionPerformed
        try {
            processo.abrirRisco(principal);
        } catch (CloneNotSupportedException ex) {
           JOptionPane.showMessageDialog(null, "Falha no Risco", "Erro ao abrir Risco!", JOptionPane.ERROR_MESSAGE, null);
            
        }
    }//GEN-LAST:event_jButtonRiscoActionPerformed

    private void jButtonMitigacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMitigacaoActionPerformed
        try {
            processo.abrirMitigacao(principal);
        } catch (CloneNotSupportedException ex) {
           JOptionPane.showMessageDialog(null, "Falha na Mitigacao", "Erro ao abrir Mitigacao!", JOptionPane.ERROR_MESSAGE, null);
            
        }
    }//GEN-LAST:event_jButtonMitigacaoActionPerformed

    public void setProcesso(ControllProcessos processo) {
        this.processo = processo;
    }

    public void setPrincipal(main principal) {
        this.principal = principal;
    }

    public void setjLabelNomeProcesso(JLabel jLabelNomeProcesso) {
        this.jLabelNomeProcesso = jLabelNomeProcesso;
    }

    public ControllProcessos getProcesso() {
        return processo;
    }

    public main getPrincipal() {
        return principal;
    }

    public JLabel getjLabelNomeProcesso() {
        return jLabelNomeProcesso;
    }

    public JButton getjButtonObjeto() {
        return jButtonObjeto;
    }

    public JButton getjButtonRisco() {
        return jButtonRisco;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMapa;
    private javax.swing.JButton jButtonMitigacao;
    private javax.swing.JButton jButtonObjeto;
    private javax.swing.JButton jButtonRisco;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelNomeProcesso;
    // End of variables declaration//GEN-END:variables


}
